--- 
environment: development
#chdir: /var/www/downforeveryoneorjustme.com
address: 127.0.0.1 
#user: nobody
#group: nobody
#port: 4567
pid: /tmp/thin.pid 
rackup: config.ru 
log: /tmp/thin.log 
max_conns: 1024 
timeout: 30 
max_persistent_conns: 512 
daemonize: false
socket: /tmp/thin.sock