--- 
environment: production
chdir: /var/www/downforeveryoneorjustme.com
address: 127.0.0.1 
pid: /tmp/thin.pid 
rackup: /var/www/downforeveryoneorjustme.com/config.ru 
log: /tmp/thin.log 
max_conns: 1024 
timeout: 30 
max_persistent_conns: 512 
daemonize: true
servers: 4
socket: /tmp/thin.sock